a = input('digite algo:')
print('O tipo primitivo desse valor é:', type(a))
print('Ele só tem espaços?',a.isspace())
print('É numérico?',a.isnumeric())
print('É alfabético?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Está em maiusculas?',a.isupper())
print('Está em minusculas?',a.islower())
print('está capitalizado?',a.istitle())
