n1 = int(input('primeiro valor:'))
n2 = int(input('segundo valor:'))
print('entre esses numeros:')
print('A soma é {} \nA subtração é {}'.format(n1+n2, n1-n2), end=' >>> ')
print('A multiplicação é {}'.format(n1*n2))
print('A potencia é {}'.format(n1**n2))
print('A divisão é {:.3f}'.format(n1/n2))
print('A divisão inteira é {}'.format(n1//n2))
print('o resto da divisão é {}'.format(n1%n2))
